
services:
  # Il "cervello" in Python (FastAPI) 
  backend:
    build: ./backend
    container_name: dms_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1

  # L'interfaccia utente in React 
  frontend:
    build: ./frontend
    container_name: dms_react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true